/* This file was auto-generated by KreMLin! */

#include "Hacl_Curve25519.h"
#include "x86intrin.h"
#include "immintrin.h"

static inline K___uint8_t_uint64_t Hacl_Bignum_addcarry_u64(uint8_t carry, uint64_t a, uint64_t b)
{
  K___uint8_t_uint64_t res;
  res.fst = _addcarry_u64(carry,a,b,&res.snd);
  return res;
}

static inline K___uint8_t_uint64_t Hacl_Bignum_subborrow_u64(uint8_t carry, uint64_t a, uint64_t b)
{
  K___uint8_t_uint64_t res;
  res.fst = _subborrow_u64(carry,a,b,&res.snd);
  return res;
}

static inline K___uint64_t_uint64_t Hacl_Bignum_mulx_u64(uint64_t a, uint64_t b)
{
  K___uint64_t_uint64_t res;
  res.snd = _mulx_u64(a,b,&res.fst);
  return res;
}

inline static K___uint8_t_uint64_t
Hacl_Bignum_fmul_by_word(
  uint64_t *tmp,
  uint64_t *input2,
  uint64_t word,
  uint32_t j,
  uint8_t c,
  uint64_t h0,
  uint64_t h1
)
{
  if (j < (uint32_t)4U)
  {
    uint64_t uu____2003 = input2[j];
    K___uint64_t_uint64_t uu____1998 = Hacl_Bignum_mulx_u64(word, uu____2003);
    K___uint64_t_uint64_t scrut = uu____1998;
    uint64_t h11 = scrut.fst;
    uint64_t low = scrut.snd;
    K___uint8_t_uint64_t uu____2030 = Hacl_Bignum_addcarry_u64(c, low, h0);
    K___uint8_t_uint64_t scrut0 = uu____2030;
    uint8_t c1 = scrut0.fst;
    uint64_t tmpj1 = scrut0.snd;
    tmp[j] = tmpj1;
    return Hacl_Bignum_fmul_by_word(tmp, input2, word, j + (uint32_t)1U, c1, h11, h11);
  }
  else
    return ((K___uint8_t_uint64_t){ .fst = c, .snd = h0 });
}

inline static K___K___uint8_t_uint8_t_uint64_t
Hacl_Bignum_fmul_inner(
  uint64_t *tmp,
  uint64_t word,
  uint64_t *input2,
  uint32_t i,
  uint32_t j,
  uint8_t c,
  uint8_t d,
  uint64_t h0,
  uint64_t h1
)
{
  if (j < (uint32_t)4U)
  {
    uint64_t tmpij = tmp[i + j];
    uint64_t uu____2193 = input2[j];
    K___uint64_t_uint64_t uu____2188 = Hacl_Bignum_mulx_u64(word, uu____2193);
    K___uint64_t_uint64_t scrut = uu____2188;
    uint64_t h11 = scrut.fst;
    uint64_t low = scrut.snd;
    K___uint8_t_uint64_t uu____2224 = Hacl_Bignum_addcarry_u64(c, low, h0);
    K___uint8_t_uint64_t scrut0 = uu____2224;
    uint8_t c1 = scrut0.fst;
    uint64_t h01 = scrut0.snd;
    K___uint8_t_uint64_t uu____2239 = Hacl_Bignum_addcarry_u64(d, tmpij, h01);
    K___uint8_t_uint64_t scrut1 = uu____2239;
    uint8_t d1 = scrut1.fst;
    uint64_t tmpij1 = scrut1.snd;
    tmp[i + j] = tmpij1;
    return Hacl_Bignum_fmul_inner(tmp, word, input2, i, j + (uint32_t)1U, c1, d1, h11, h11);
  }
  else
    return ((K___K___uint8_t_uint8_t_uint64_t){ .fst = { .fst = c, .snd = d }, .snd = h0 });
}

inline static void
Hacl_Bignum_fmul_(
  uint64_t *tmp,
  uint64_t *input1,
  uint64_t *input2,
  uint32_t i,
  uint8_t c,
  uint8_t d,
  uint64_t h0,
  uint64_t h1
)
{
  if (i < (uint32_t)4U)
  {
    uint64_t tmpi = tmp[i];
    uint64_t input1i = input1[i];
    uint64_t uu____2433 = input2[0U];
    K___uint64_t_uint64_t uu____2428 = Hacl_Bignum_mulx_u64(input1i, uu____2433);
    K___uint64_t_uint64_t scrut = uu____2428;
    uint64_t h01 = scrut.fst;
    uint64_t low = scrut.snd;
    K___uint8_t_uint64_t uu____2456 = Hacl_Bignum_addcarry_u64(d, tmpi, low);
    K___uint8_t_uint64_t scrut0 = uu____2456;
    uint8_t d1 = scrut0.fst;
    uint64_t tmpi1 = scrut0.snd;
    tmp[i] = tmpi1;
    uint8_t c1 = (uint8_t)0U;
    K___K___uint8_t_uint8_t_uint64_t
    uu____2467 = Hacl_Bignum_fmul_inner(tmp, input1i, input2, i, (uint32_t)1U, c1, d1, h01, h1);
    uint64_t h02 = uu____2467.snd;
    uint8_t d2 = uu____2467.fst.snd;
    uint8_t c2 = uu____2467.fst.fst;
    K___uint8_t_uint64_t uu____2506 = Hacl_Bignum_addcarry_u64(c2, h02, (uint64_t)0U);
    K___uint8_t_uint64_t scrut1 = uu____2506;
    uint8_t c3 = scrut1.fst;
    uint64_t h03 = scrut1.snd;
    (void)tmp[i + (uint32_t)4U];
    K___uint8_t_uint64_t uu____2516 = Hacl_Bignum_addcarry_u64(d2, h03, (uint64_t)0U);
    K___uint8_t_uint64_t scrut2 = uu____2516;
    uint8_t d3 = scrut2.fst;
    uint64_t tmpi41 = scrut2.snd;
    tmp[i + (uint32_t)4U] = tmpi41;
    Hacl_Bignum_fmul_(tmp, input1, input2, i + (uint32_t)1U, c3, d3, h03, h1);
  }
}

inline static void Hacl_Bignum_fmul(uint64_t *output, uint64_t *input1, uint64_t *input2)
{
  uint64_t tmp[8U] = { 0U };
  uint64_t uu____2775 = input1[0U];
  uint64_t uu____2796 = input2[0U];
  K___uint64_t_uint64_t uu____2770 = Hacl_Bignum_mulx_u64(uu____2775, uu____2796);
  K___uint64_t_uint64_t scrut = uu____2770;
  uint64_t h0 = scrut.fst;
  uint64_t tmp01 = scrut.snd;
  tmp[0U] = tmp01;
  uint8_t c = (uint8_t)0U;
  uint8_t d = (uint8_t)0U;
  uint64_t uu____2829 = input1[0U];
  K___uint8_t_uint64_t
  uu____2824 =
    Hacl_Bignum_fmul_by_word(tmp,
      input2,
      uu____2829,
      (uint32_t)1U,
      c,
      h0,
      (uint64_t)0U);
  K___uint8_t_uint64_t scrut0 = uu____2824;
  uint8_t c1 = scrut0.fst;
  uint64_t h01 = scrut0.snd;
  K___uint8_t_uint64_t uu____2878 = Hacl_Bignum_addcarry_u64(c1, h01, (uint64_t)0U);
  K___uint8_t_uint64_t scrut1 = uu____2878;
  uint8_t c2 = scrut1.fst;
  uint64_t tmp41 = scrut1.snd;
  tmp[4U] = tmp41;
  Hacl_Bignum_fmul_(tmp, input1, input2, (uint32_t)1U, c2, d, h01, (uint64_t)0U);
  uint64_t tmp02 = tmp[0U];
  uint64_t tmp1 = tmp[1U];
  uint64_t tmp2 = tmp[2U];
  uint64_t tmp3 = tmp[3U];
  uint64_t tmp42 = tmp[4U];
  uint64_t tmp5 = tmp[5U];
  uint64_t tmp6 = tmp[6U];
  uint64_t tmp7 = tmp[7U];
  uint8_t c3 = (uint8_t)0U;
  uint8_t d1 = (uint8_t)0U;
  K___uint64_t_uint64_t uu____2958 = Hacl_Bignum_mulx_u64(tmp42, (uint64_t)38U);
  K___uint64_t_uint64_t scrut2 = uu____2958;
  uint64_t h02 = scrut2.fst;
  uint64_t low = scrut2.snd;
  K___uint8_t_uint64_t uu____2965 = Hacl_Bignum_addcarry_u64(c3, tmp02, low);
  K___uint8_t_uint64_t scrut3 = uu____2965;
  uint8_t c4 = scrut3.fst;
  uint64_t tmp03 = scrut3.snd;
  K___uint64_t_uint64_t uu____2972 = Hacl_Bignum_mulx_u64(tmp5, (uint64_t)38U);
  K___uint64_t_uint64_t scrut4 = uu____2972;
  uint64_t h1 = scrut4.fst;
  uint64_t low1 = scrut4.snd;
  K___uint8_t_uint64_t uu____2979 = Hacl_Bignum_addcarry_u64(c4, tmp1, low1);
  K___uint8_t_uint64_t scrut5 = uu____2979;
  uint8_t c5 = scrut5.fst;
  uint64_t tmp11 = scrut5.snd;
  K___uint8_t_uint64_t uu____2986 = Hacl_Bignum_addcarry_u64(d1, tmp11, h02);
  K___uint8_t_uint64_t scrut6 = uu____2986;
  uint8_t d2 = scrut6.fst;
  uint64_t tmp12 = scrut6.snd;
  uint64_t h03 = h1;
  K___uint64_t_uint64_t uu____2994 = Hacl_Bignum_mulx_u64(tmp6, (uint64_t)38U);
  K___uint64_t_uint64_t scrut7 = uu____2994;
  uint64_t h11 = scrut7.fst;
  uint64_t low2 = scrut7.snd;
  K___uint8_t_uint64_t uu____3001 = Hacl_Bignum_addcarry_u64(c5, tmp2, low2);
  K___uint8_t_uint64_t scrut8 = uu____3001;
  uint8_t c6 = scrut8.fst;
  uint64_t tmp21 = scrut8.snd;
  K___uint8_t_uint64_t uu____3008 = Hacl_Bignum_addcarry_u64(d2, tmp21, h03);
  K___uint8_t_uint64_t scrut9 = uu____3008;
  uint8_t d3 = scrut9.fst;
  uint64_t tmp22 = scrut9.snd;
  uint64_t h04 = h11;
  K___uint64_t_uint64_t uu____3016 = Hacl_Bignum_mulx_u64(tmp7, (uint64_t)38U);
  K___uint64_t_uint64_t scrut10 = uu____3016;
  uint64_t h12 = scrut10.fst;
  uint64_t low3 = scrut10.snd;
  K___uint8_t_uint64_t uu____3023 = Hacl_Bignum_addcarry_u64(c6, tmp3, low3);
  K___uint8_t_uint64_t scrut11 = uu____3023;
  uint8_t c7 = scrut11.fst;
  uint64_t tmp31 = scrut11.snd;
  K___uint8_t_uint64_t uu____3030 = Hacl_Bignum_addcarry_u64(d3, tmp31, h04);
  K___uint8_t_uint64_t scrut12 = uu____3030;
  uint8_t d4 = scrut12.fst;
  uint64_t tmp32 = scrut12.snd;
  K___uint8_t_uint64_t uu____3037 = Hacl_Bignum_addcarry_u64(c7, h12, (uint64_t)0U);
  K___uint8_t_uint64_t scrut13 = uu____3037;
  uint64_t h13 = scrut13.snd;
  K___uint8_t_uint64_t uu____3044 = Hacl_Bignum_addcarry_u64(d4, h13, (uint64_t)0U);
  K___uint8_t_uint64_t scrut14 = uu____3044;
  uint64_t h14 = scrut14.snd;
  uint64_t h15 = (uint64_t)38U * h14;
  uint8_t c9 = (uint8_t)0U;
  K___uint8_t_uint64_t uu____3053 = Hacl_Bignum_addcarry_u64(c9, tmp03, h15);
  K___uint8_t_uint64_t scrut15 = uu____3053;
  uint8_t c10 = scrut15.fst;
  uint64_t tmp04 = scrut15.snd;
  K___uint8_t_uint64_t uu____3060 = Hacl_Bignum_addcarry_u64(c10, tmp12, (uint64_t)0U);
  K___uint8_t_uint64_t scrut16 = uu____3060;
  uint8_t c11 = scrut16.fst;
  uint64_t tmp13 = scrut16.snd;
  K___uint8_t_uint64_t uu____3067 = Hacl_Bignum_addcarry_u64(c11, tmp22, (uint64_t)0U);
  K___uint8_t_uint64_t scrut17 = uu____3067;
  uint8_t c12 = scrut17.fst;
  uint64_t tmp23 = scrut17.snd;
  K___uint8_t_uint64_t uu____3074 = Hacl_Bignum_addcarry_u64(c12, tmp32, (uint64_t)0U);
  K___uint8_t_uint64_t scrut18 = uu____3074;
  uint8_t c13 = scrut18.fst;
  uint64_t tmp33 = scrut18.snd;
  uint64_t h16 = (uint64_t)38U * (uint64_t)c13;
  uint8_t c14 = (uint8_t)0U;
  K___uint8_t_uint64_t uu____3083 = Hacl_Bignum_addcarry_u64(c14, tmp04, h16);
  K___uint8_t_uint64_t scrut19 = uu____3083;
  uint8_t c15 = scrut19.fst;
  uint64_t tmp05 = scrut19.snd;
  K___uint8_t_uint64_t uu____3090 = Hacl_Bignum_addcarry_u64(c15, tmp13, (uint64_t)0U);
  K___uint8_t_uint64_t scrut20 = uu____3090;
  uint8_t c16 = scrut20.fst;
  uint64_t tmp14 = scrut20.snd;
  K___uint8_t_uint64_t uu____3097 = Hacl_Bignum_addcarry_u64(c16, tmp23, (uint64_t)0U);
  K___uint8_t_uint64_t scrut21 = uu____3097;
  uint8_t c17 = scrut21.fst;
  uint64_t tmp24 = scrut21.snd;
  K___uint8_t_uint64_t uu____3104 = Hacl_Bignum_addcarry_u64(c17, tmp33, (uint64_t)0U);
  K___uint8_t_uint64_t scrut22 = uu____3104;
  uint64_t tmp34 = scrut22.snd;
  output[0U] = tmp05;
  output[1U] = tmp14;
  output[2U] = tmp24;
  output[3U] = tmp34;
}

inline static void Hacl_Bignum_fsquare(uint64_t *input)
{
  Hacl_Bignum_fmul(input, input, input);
}

inline static void Hacl_Bignum_Fmul_fmul(uint64_t *output, uint64_t *input, uint64_t *input21)
{
  Hacl_Bignum_fmul(output, input, input21);
}

inline static void
Hacl_Bignum_Fsquare_fsquare_times(uint64_t *output, uint64_t *input, uint32_t count1)
{
  memcpy(output, input, (uint32_t)5U * sizeof input[0U]);
  Hacl_Bignum_fsquare(output);
  for (uint32_t i = (uint32_t)1U; i < count1; i = i + (uint32_t)1U)
    Hacl_Bignum_fsquare(output);
}

inline static void Hacl_Bignum_Fsquare_fsquare_times_inplace(uint64_t *output, uint32_t count1)
{
  Hacl_Bignum_fsquare(output);
  for (uint32_t i = (uint32_t)1U; i < count1; i = i + (uint32_t)1U)
    Hacl_Bignum_fsquare(output);
}

inline static void Hacl_Bignum_Crecip_crecip(uint64_t *out, uint64_t *z)
{
  uint64_t buf[20U] = { 0U };
  uint64_t *a = buf;
  uint64_t *t00 = buf + (uint32_t)5U;
  uint64_t *b0 = buf + (uint32_t)10U;
  Hacl_Bignum_Fsquare_fsquare_times(a, z, (uint32_t)1U);
  Hacl_Bignum_Fsquare_fsquare_times(t00, a, (uint32_t)2U);
  Hacl_Bignum_Fmul_fmul(b0, t00, z);
  Hacl_Bignum_Fmul_fmul(a, b0, a);
  Hacl_Bignum_Fsquare_fsquare_times(t00, a, (uint32_t)1U);
  Hacl_Bignum_Fmul_fmul(b0, t00, b0);
  Hacl_Bignum_Fsquare_fsquare_times(t00, b0, (uint32_t)5U);
  uint64_t *t01 = buf + (uint32_t)5U;
  uint64_t *b1 = buf + (uint32_t)10U;
  uint64_t *c0 = buf + (uint32_t)15U;
  Hacl_Bignum_Fmul_fmul(b1, t01, b1);
  Hacl_Bignum_Fsquare_fsquare_times(t01, b1, (uint32_t)10U);
  Hacl_Bignum_Fmul_fmul(c0, t01, b1);
  Hacl_Bignum_Fsquare_fsquare_times(t01, c0, (uint32_t)20U);
  Hacl_Bignum_Fmul_fmul(t01, t01, c0);
  Hacl_Bignum_Fsquare_fsquare_times_inplace(t01, (uint32_t)10U);
  Hacl_Bignum_Fmul_fmul(b1, t01, b1);
  Hacl_Bignum_Fsquare_fsquare_times(t01, b1, (uint32_t)50U);
  uint64_t *a0 = buf;
  uint64_t *t0 = buf + (uint32_t)5U;
  uint64_t *b = buf + (uint32_t)10U;
  uint64_t *c = buf + (uint32_t)15U;
  Hacl_Bignum_Fmul_fmul(c, t0, b);
  Hacl_Bignum_Fsquare_fsquare_times(t0, c, (uint32_t)100U);
  Hacl_Bignum_Fmul_fmul(t0, t0, c);
  Hacl_Bignum_Fsquare_fsquare_times_inplace(t0, (uint32_t)50U);
  Hacl_Bignum_Fmul_fmul(t0, t0, b);
  Hacl_Bignum_Fsquare_fsquare_times_inplace(t0, (uint32_t)5U);
  Hacl_Bignum_Fmul_fmul(out, t0, a0);
}

inline static void Hacl_Bignum_Fdifference_fdifference(uint64_t *a, uint64_t *b)
{
  uint64_t a0 = a[0U];
  uint64_t a1 = a[1U];
  uint64_t a2 = a[2U];
  uint64_t a3 = a[3U];
  uint64_t b0 = b[0U];
  uint64_t b1 = b[1U];
  uint64_t b2 = b[2U];
  uint64_t b3 = b[3U];
  uint8_t c = (uint8_t)0U;
  K___uint8_t_uint64_t
  uu____1268 = Hacl_Bignum_addcarry_u64(c, b0, (uint64_t)0xffffffffffffffdaU);
  K___uint8_t_uint64_t scrut = uu____1268;
  uint8_t c1 = scrut.fst;
  uint64_t tmp0 = scrut.snd;
  K___uint8_t_uint64_t
  uu____1275 = Hacl_Bignum_addcarry_u64(c1, b1, (uint64_t)0xffffffffffffffffU);
  K___uint8_t_uint64_t scrut0 = uu____1275;
  uint8_t c2 = scrut0.fst;
  uint64_t tmp1 = scrut0.snd;
  K___uint8_t_uint64_t
  uu____1282 = Hacl_Bignum_addcarry_u64(c2, b2, (uint64_t)0xffffffffffffffffU);
  K___uint8_t_uint64_t scrut1 = uu____1282;
  uint8_t c3 = scrut1.fst;
  uint64_t tmp2 = scrut1.snd;
  K___uint8_t_uint64_t
  uu____1289 = Hacl_Bignum_addcarry_u64(c3, b3, (uint64_t)0xffffffffffffffffU);
  K___uint8_t_uint64_t scrut2 = uu____1289;
  uint8_t c4 = scrut2.fst;
  uint64_t tmp3 = scrut2.snd;
  K___uint8_t_uint64_t uu____1296 = Hacl_Bignum_addcarry_u64(c4, (uint64_t)0U, (uint64_t)0U);
  K___uint8_t_uint64_t scrut3 = uu____1296;
  uint64_t tmp4 = scrut3.snd;
  uint8_t c6 = (uint8_t)0U;
  K___uint8_t_uint64_t uu____1304 = Hacl_Bignum_subborrow_u64(c6, tmp0, a0);
  K___uint8_t_uint64_t scrut4 = uu____1304;
  uint8_t c7 = scrut4.fst;
  uint64_t tmp01 = scrut4.snd;
  K___uint8_t_uint64_t uu____1311 = Hacl_Bignum_subborrow_u64(c7, tmp1, a1);
  K___uint8_t_uint64_t scrut5 = uu____1311;
  uint8_t c8 = scrut5.fst;
  uint64_t tmp11 = scrut5.snd;
  K___uint8_t_uint64_t uu____1318 = Hacl_Bignum_subborrow_u64(c8, tmp2, a2);
  K___uint8_t_uint64_t scrut6 = uu____1318;
  uint8_t c9 = scrut6.fst;
  uint64_t tmp21 = scrut6.snd;
  K___uint8_t_uint64_t uu____1325 = Hacl_Bignum_subborrow_u64(c9, tmp3, a3);
  K___uint8_t_uint64_t scrut7 = uu____1325;
  uint8_t c10 = scrut7.fst;
  uint64_t tmp31 = scrut7.snd;
  K___uint8_t_uint64_t uu____1332 = Hacl_Bignum_subborrow_u64(c10, tmp4, (uint64_t)0U);
  K___uint8_t_uint64_t scrut8 = uu____1332;
  uint64_t tmp41 = scrut8.snd;
  uint64_t top = (uint64_t)38U * tmp41;
  uint8_t c12 = (uint8_t)0U;
  K___uint8_t_uint64_t uu____1341 = Hacl_Bignum_addcarry_u64(c12, tmp01, top);
  K___uint8_t_uint64_t scrut9 = uu____1341;
  uint8_t c13 = scrut9.fst;
  uint64_t tmp02 = scrut9.snd;
  K___uint8_t_uint64_t uu____1348 = Hacl_Bignum_addcarry_u64(c13, tmp11, (uint64_t)0U);
  K___uint8_t_uint64_t scrut10 = uu____1348;
  uint8_t c14 = scrut10.fst;
  uint64_t tmp12 = scrut10.snd;
  K___uint8_t_uint64_t uu____1355 = Hacl_Bignum_addcarry_u64(c14, tmp21, (uint64_t)0U);
  K___uint8_t_uint64_t scrut11 = uu____1355;
  uint8_t c15 = scrut11.fst;
  uint64_t tmp22 = scrut11.snd;
  K___uint8_t_uint64_t uu____1362 = Hacl_Bignum_addcarry_u64(c15, tmp31, (uint64_t)0U);
  K___uint8_t_uint64_t scrut12 = uu____1362;
  uint8_t c16 = scrut12.fst;
  uint64_t tmp32 = scrut12.snd;
  uint64_t top1 = (uint64_t)38U * (uint64_t)c16;
  uint8_t c17 = (uint8_t)0U;
  K___uint8_t_uint64_t uu____1371 = Hacl_Bignum_addcarry_u64(c17, tmp02, top1);
  K___uint8_t_uint64_t scrut13 = uu____1371;
  uint8_t c18 = scrut13.fst;
  uint64_t tmp03 = scrut13.snd;
  K___uint8_t_uint64_t uu____1378 = Hacl_Bignum_addcarry_u64(c18, tmp12, (uint64_t)0U);
  K___uint8_t_uint64_t scrut14 = uu____1378;
  uint8_t c19 = scrut14.fst;
  uint64_t tmp13 = scrut14.snd;
  K___uint8_t_uint64_t uu____1385 = Hacl_Bignum_addcarry_u64(c19, tmp22, (uint64_t)0U);
  K___uint8_t_uint64_t scrut15 = uu____1385;
  uint8_t c20 = scrut15.fst;
  uint64_t tmp23 = scrut15.snd;
  K___uint8_t_uint64_t uu____1392 = Hacl_Bignum_addcarry_u64(c20, tmp32, (uint64_t)0U);
  K___uint8_t_uint64_t scrut16 = uu____1392;
  uint64_t tmp33 = scrut16.snd;
  a[0U] = tmp03;
  a[1U] = tmp13;
  a[2U] = tmp23;
  a[3U] = tmp33;
}

inline static void Hacl_Bignum_Fscalar_fscalar(uint64_t *output, uint64_t *b, uint64_t s)
{
  uint64_t b0 = b[0U];
  uint64_t b1 = b[1U];
  uint64_t b2 = b[2U];
  uint64_t b3 = b[3U];
  K___uint64_t_uint64_t uu____1701 = Hacl_Bignum_mulx_u64(b0, s);
  K___uint64_t_uint64_t scrut = uu____1701;
  uint64_t h0 = scrut.fst;
  uint64_t l0 = scrut.snd;
  K___uint64_t_uint64_t uu____1708 = Hacl_Bignum_mulx_u64(b1, s);
  K___uint64_t_uint64_t scrut0 = uu____1708;
  uint64_t h1 = scrut0.fst;
  uint64_t l1 = scrut0.snd;
  K___uint64_t_uint64_t uu____1715 = Hacl_Bignum_mulx_u64(b2, s);
  K___uint64_t_uint64_t scrut1 = uu____1715;
  uint64_t h2 = scrut1.fst;
  uint64_t l2 = scrut1.snd;
  K___uint64_t_uint64_t uu____1722 = Hacl_Bignum_mulx_u64(b3, s);
  K___uint64_t_uint64_t scrut2 = uu____1722;
  uint64_t h3 = scrut2.fst;
  uint64_t l3 = scrut2.snd;
  uint8_t c = (uint8_t)0U;
  K___uint8_t_uint64_t uu____1730 = Hacl_Bignum_addcarry_u64(c, l1, h0);
  K___uint8_t_uint64_t scrut3 = uu____1730;
  uint8_t c1 = scrut3.fst;
  uint64_t l11 = scrut3.snd;
  K___uint8_t_uint64_t uu____1737 = Hacl_Bignum_addcarry_u64(c1, l2, h1);
  K___uint8_t_uint64_t scrut4 = uu____1737;
  uint8_t c2 = scrut4.fst;
  uint64_t l21 = scrut4.snd;
  K___uint8_t_uint64_t uu____1744 = Hacl_Bignum_addcarry_u64(c2, l3, h2);
  K___uint8_t_uint64_t scrut5 = uu____1744;
  uint8_t c3 = scrut5.fst;
  uint64_t l31 = scrut5.snd;
  K___uint8_t_uint64_t uu____1751 = Hacl_Bignum_addcarry_u64(c3, (uint64_t)0U, h3);
  K___uint8_t_uint64_t scrut6 = uu____1751;
  uint64_t l4 = scrut6.snd;
  K___uint64_t_uint64_t uu____1758 = Hacl_Bignum_mulx_u64(l4, (uint64_t)38U);
  K___uint64_t_uint64_t scrut7 = uu____1758;
  uint64_t h4 = scrut7.fst;
  uint64_t l41 = scrut7.snd;
  uint8_t c5 = (uint8_t)0U;
  K___uint8_t_uint64_t uu____1766 = Hacl_Bignum_addcarry_u64(c5, l0, l41);
  K___uint8_t_uint64_t scrut8 = uu____1766;
  uint8_t c6 = scrut8.fst;
  uint64_t l01 = scrut8.snd;
  K___uint8_t_uint64_t uu____1773 = Hacl_Bignum_addcarry_u64(c6, l11, h4);
  K___uint8_t_uint64_t scrut9 = uu____1773;
  uint8_t c7 = scrut9.fst;
  uint64_t l12 = scrut9.snd;
  K___uint8_t_uint64_t uu____1780 = Hacl_Bignum_addcarry_u64(c7, l21, (uint64_t)0U);
  K___uint8_t_uint64_t scrut10 = uu____1780;
  uint8_t c8 = scrut10.fst;
  uint64_t l22 = scrut10.snd;
  K___uint8_t_uint64_t uu____1787 = Hacl_Bignum_addcarry_u64(c8, l31, (uint64_t)0U);
  K___uint8_t_uint64_t scrut11 = uu____1787;
  uint8_t c9 = scrut11.fst;
  uint64_t l32 = scrut11.snd;
  uint64_t l42 = (uint64_t)38U * (uint64_t)c9;
  uint8_t c10 = (uint8_t)0U;
  K___uint8_t_uint64_t uu____1796 = Hacl_Bignum_addcarry_u64(c10, l01, l42);
  K___uint8_t_uint64_t scrut12 = uu____1796;
  uint8_t c11 = scrut12.fst;
  uint64_t l02 = scrut12.snd;
  K___uint8_t_uint64_t uu____1803 = Hacl_Bignum_addcarry_u64(c11, l12, (uint64_t)0U);
  K___uint8_t_uint64_t scrut13 = uu____1803;
  uint8_t c12 = scrut13.fst;
  uint64_t l13 = scrut13.snd;
  K___uint8_t_uint64_t uu____1810 = Hacl_Bignum_addcarry_u64(c12, l22, (uint64_t)0U);
  K___uint8_t_uint64_t scrut14 = uu____1810;
  uint8_t c13 = scrut14.fst;
  uint64_t l23 = scrut14.snd;
  K___uint8_t_uint64_t uu____1817 = Hacl_Bignum_addcarry_u64(c13, l32, (uint64_t)0U);
  K___uint8_t_uint64_t scrut15 = uu____1817;
  uint64_t l33 = scrut15.snd;
  output[0U] = l02;
  output[1U] = l13;
  output[2U] = l23;
  output[3U] = l33;
}

inline static void Hacl_Bignum_Fsum_fsum(uint64_t *a, uint64_t *b)
{
  uint64_t a0 = a[0U];
  uint64_t a1 = a[1U];
  uint64_t a2 = a[2U];
  uint64_t a3 = a[3U];
  uint64_t b0 = b[0U];
  uint64_t b1 = b[1U];
  uint64_t b2 = b[2U];
  uint64_t b3 = b[3U];
  uint8_t c = (uint8_t)0U;
  K___uint8_t_uint64_t uu____818 = Hacl_Bignum_addcarry_u64(c, a0, b0);
  K___uint8_t_uint64_t scrut = uu____818;
  uint8_t c1 = scrut.fst;
  uint64_t a01 = scrut.snd;
  K___uint8_t_uint64_t uu____825 = Hacl_Bignum_addcarry_u64(c1, a1, b1);
  K___uint8_t_uint64_t scrut0 = uu____825;
  uint8_t c2 = scrut0.fst;
  uint64_t a11 = scrut0.snd;
  K___uint8_t_uint64_t uu____832 = Hacl_Bignum_addcarry_u64(c2, a2, b2);
  K___uint8_t_uint64_t scrut1 = uu____832;
  uint8_t c3 = scrut1.fst;
  uint64_t a21 = scrut1.snd;
  K___uint8_t_uint64_t uu____839 = Hacl_Bignum_addcarry_u64(c3, a3, b3);
  K___uint8_t_uint64_t scrut2 = uu____839;
  uint8_t c4 = scrut2.fst;
  uint64_t a31 = scrut2.snd;
  uint64_t top = (uint64_t)38U * (uint64_t)c4;
  uint8_t c5 = (uint8_t)0U;
  K___uint8_t_uint64_t uu____849 = Hacl_Bignum_addcarry_u64(c5, a01, top);
  K___uint8_t_uint64_t scrut3 = uu____849;
  uint8_t c6 = scrut3.fst;
  uint64_t a02 = scrut3.snd;
  K___uint8_t_uint64_t uu____856 = Hacl_Bignum_addcarry_u64(c6, a11, (uint64_t)0U);
  K___uint8_t_uint64_t scrut4 = uu____856;
  uint8_t c7 = scrut4.fst;
  uint64_t a12 = scrut4.snd;
  K___uint8_t_uint64_t uu____863 = Hacl_Bignum_addcarry_u64(c7, a21, (uint64_t)0U);
  K___uint8_t_uint64_t scrut5 = uu____863;
  uint8_t c8 = scrut5.fst;
  uint64_t a22 = scrut5.snd;
  K___uint8_t_uint64_t uu____870 = Hacl_Bignum_addcarry_u64(c8, a31, (uint64_t)0U);
  K___uint8_t_uint64_t scrut6 = uu____870;
  uint64_t a32 = scrut6.snd;
  a[0U] = a02;
  a[1U] = a12;
  a[2U] = a22;
  a[3U] = a32;
}

static void
Hacl_EC_Point_swap_conditional_step(uint64_t *a, uint64_t *b, uint64_t swap1, uint32_t ctr)
{
  uint32_t i = ctr - (uint32_t)1U;
  uint64_t ai = a[i];
  uint64_t bi = b[i];
  uint64_t x = swap1 & (ai ^ bi);
  uint64_t ai1 = ai ^ x;
  uint64_t bi1 = bi ^ x;
  a[i] = ai1;
  b[i] = bi1;
}

static void
Hacl_EC_Point_swap_conditional_(uint64_t *a, uint64_t *b, uint64_t swap1, uint32_t ctr)
{
  if (!(ctr == (uint32_t)0U))
  {
    Hacl_EC_Point_swap_conditional_step(a, b, swap1, ctr);
    uint32_t i = ctr - (uint32_t)1U;
    Hacl_EC_Point_swap_conditional_(a, b, swap1, i);
  }
}

static void Hacl_EC_Point_swap_conditional(uint64_t *a, uint64_t *b, uint64_t iswap)
{
  uint64_t swap1 = (uint64_t)0U - iswap;
  Hacl_EC_Point_swap_conditional_(a, b, swap1, (uint32_t)5U);
  Hacl_EC_Point_swap_conditional_(a + (uint32_t)5U, b + (uint32_t)5U, swap1, (uint32_t)5U);
}

static void Hacl_EC_Point_copy(uint64_t *output, uint64_t *input)
{
  memcpy(output, input, (uint32_t)5U * sizeof input[0U]);
  memcpy(output + (uint32_t)5U,
    input + (uint32_t)5U,
    (uint32_t)5U * sizeof (input + (uint32_t)5U)[0U]);
}

static void
Hacl_EC_AddAndDouble_fmonty(
  uint64_t *pp,
  uint64_t *ppq,
  uint64_t *p,
  uint64_t *pq,
  uint64_t *qmqp
)
{
  uint64_t *qx = qmqp;
  uint64_t *x2 = pp;
  uint64_t *z2 = pp + (uint32_t)5U;
  uint64_t *x3 = ppq;
  uint64_t *z3 = ppq + (uint32_t)5U;
  uint64_t *x = p;
  uint64_t *z = p + (uint32_t)5U;
  uint64_t *xprime = pq;
  uint64_t *zprime = pq + (uint32_t)5U;
  uint64_t buf[40U] = { 0U };
  uint64_t *origx = buf;
  uint64_t *origxprime = buf + (uint32_t)5U;
  uint64_t *xxprime0 = buf + (uint32_t)25U;
  uint64_t *zzprime0 = buf + (uint32_t)30U;
  memcpy(origx, x, (uint32_t)5U * sizeof x[0U]);
  Hacl_Bignum_Fsum_fsum(x, z);
  Hacl_Bignum_Fdifference_fdifference(z, origx);
  memcpy(origxprime, xprime, (uint32_t)5U * sizeof xprime[0U]);
  Hacl_Bignum_Fsum_fsum(xprime, zprime);
  Hacl_Bignum_Fdifference_fdifference(zprime, origxprime);
  Hacl_Bignum_Fmul_fmul(xxprime0, xprime, z);
  Hacl_Bignum_Fmul_fmul(zzprime0, x, zprime);
  uint64_t *origxprime0 = buf + (uint32_t)5U;
  uint64_t *xx0 = buf + (uint32_t)15U;
  uint64_t *zz0 = buf + (uint32_t)20U;
  uint64_t *xxprime = buf + (uint32_t)25U;
  uint64_t *zzprime = buf + (uint32_t)30U;
  uint64_t *zzzprime = buf + (uint32_t)35U;
  memcpy(origxprime0, xxprime, (uint32_t)5U * sizeof xxprime[0U]);
  Hacl_Bignum_Fsum_fsum(xxprime, zzprime);
  Hacl_Bignum_Fdifference_fdifference(zzprime, origxprime0);
  Hacl_Bignum_Fsquare_fsquare_times(x3, xxprime, (uint32_t)1U);
  Hacl_Bignum_Fsquare_fsquare_times(zzzprime, zzprime, (uint32_t)1U);
  Hacl_Bignum_Fmul_fmul(z3, zzzprime, qx);
  Hacl_Bignum_Fsquare_fsquare_times(xx0, x, (uint32_t)1U);
  Hacl_Bignum_Fsquare_fsquare_times(zz0, z, (uint32_t)1U);
  uint64_t *zzz = buf + (uint32_t)10U;
  uint64_t *xx = buf + (uint32_t)15U;
  uint64_t *zz = buf + (uint32_t)20U;
  Hacl_Bignum_Fmul_fmul(x2, xx, zz);
  Hacl_Bignum_Fdifference_fdifference(zz, xx);
  uint64_t scalar = (uint64_t)121665U;
  Hacl_Bignum_Fscalar_fscalar(zzz, zz, scalar);
  Hacl_Bignum_Fsum_fsum(zzz, xx);
  Hacl_Bignum_Fmul_fmul(z2, zzz, zz);
}

static void
Hacl_EC_Ladder_SmallLoop_cmult_small_loop_step(
  uint64_t *nq,
  uint64_t *nqpq,
  uint64_t *nq2,
  uint64_t *nqpq2,
  uint64_t *q,
  uint8_t byt
)
{
  uint64_t bit = (uint64_t)(byt >> (uint32_t)7U);
  Hacl_EC_Point_swap_conditional(nq, nqpq, bit);
  Hacl_EC_AddAndDouble_fmonty(nq2, nqpq2, nq, nqpq, q);
  uint64_t bit0 = (uint64_t)(byt >> (uint32_t)7U);
  Hacl_EC_Point_swap_conditional(nq2, nqpq2, bit0);
}

static void
Hacl_EC_Ladder_SmallLoop_cmult_small_loop_double_step(
  uint64_t *nq,
  uint64_t *nqpq,
  uint64_t *nq2,
  uint64_t *nqpq2,
  uint64_t *q,
  uint8_t byt
)
{
  Hacl_EC_Ladder_SmallLoop_cmult_small_loop_step(nq, nqpq, nq2, nqpq2, q, byt);
  uint8_t byt1 = byt << (uint32_t)1U;
  Hacl_EC_Ladder_SmallLoop_cmult_small_loop_step(nq2, nqpq2, nq, nqpq, q, byt1);
}

static void
Hacl_EC_Ladder_SmallLoop_cmult_small_loop(
  uint64_t *nq,
  uint64_t *nqpq,
  uint64_t *nq2,
  uint64_t *nqpq2,
  uint64_t *q,
  uint8_t byt,
  uint32_t i
)
{
  if (!(i == (uint32_t)0U))
  {
    uint32_t i_ = i - (uint32_t)1U;
    Hacl_EC_Ladder_SmallLoop_cmult_small_loop_double_step(nq, nqpq, nq2, nqpq2, q, byt);
    uint8_t byt_ = byt << (uint32_t)2U;
    Hacl_EC_Ladder_SmallLoop_cmult_small_loop(nq, nqpq, nq2, nqpq2, q, byt_, i_);
  }
}

static void
Hacl_EC_Ladder_BigLoop_cmult_big_loop(
  uint8_t *n1,
  uint64_t *nq,
  uint64_t *nqpq,
  uint64_t *nq2,
  uint64_t *nqpq2,
  uint64_t *q,
  uint32_t i
)
{
  if (!(i == (uint32_t)0U))
  {
    uint32_t i1 = i - (uint32_t)1U;
    uint8_t byte = n1[i1];
    Hacl_EC_Ladder_SmallLoop_cmult_small_loop(nq, nqpq, nq2, nqpq2, q, byte, (uint32_t)4U);
    Hacl_EC_Ladder_BigLoop_cmult_big_loop(n1, nq, nqpq, nq2, nqpq2, q, i1);
  }
}

static void Hacl_EC_Ladder_cmult(uint64_t *result, uint8_t *n1, uint64_t *q)
{
  uint64_t point_buf[40U] = { 0U };
  uint64_t *nq = point_buf;
  uint64_t *nqpq = point_buf + (uint32_t)10U;
  uint64_t *nq2 = point_buf + (uint32_t)20U;
  uint64_t *nqpq2 = point_buf + (uint32_t)30U;
  Hacl_EC_Point_copy(nqpq, q);
  nq[0U] = (uint64_t)1U;
  Hacl_EC_Ladder_BigLoop_cmult_big_loop(n1, nq, nqpq, nq2, nqpq2, q, (uint32_t)32U);
  Hacl_EC_Point_copy(result, nq);
}

static void Hacl_EC_Format_fexpand(uint64_t *output, uint8_t *input)
{
  uint8_t *input0 = input;
  uint8_t *input1 = input + (uint32_t)8U;
  uint8_t *input2 = input + (uint32_t)16U;
  uint8_t *input3 = input + (uint32_t)24U;
  uint64_t uu____442 = load64_le(input0);
  output[0U] = uu____442;
  uint64_t uu____467 = load64_le(input1);
  output[1U] = uu____467;
  uint64_t uu____492 = load64_le(input2);
  output[2U] = uu____492;
  uint64_t uu____517 = load64_le(input3);
  uint64_t uu____516 = uu____517 & (uint64_t)0x7fffffffffffffffU;
  output[3U] = uu____516;
}

static void Hacl_EC_Format_fcontract(uint8_t *output, uint64_t *input)
{
  uint64_t top = input[3U];
  input[3U] = top & (uint64_t)0x7fffffffffffffffU;
  uint64_t input0 = input[0U];
  uint64_t input1 = input[1U];
  uint64_t input2 = input[2U];
  uint64_t input3 = input[3U];
  uint64_t top1 = (uint64_t)19U * (top >> (uint32_t)63U);
  uint8_t c = (uint8_t)0U;
  K___uint8_t_uint64_t uu____282 = Hacl_Bignum_addcarry_u64(c, input0, top1);
  K___uint8_t_uint64_t scrut = uu____282;
  uint8_t c1 = scrut.fst;
  uint64_t input01 = scrut.snd;
  K___uint8_t_uint64_t uu____289 = Hacl_Bignum_addcarry_u64(c1, input1, (uint64_t)0U);
  K___uint8_t_uint64_t scrut0 = uu____289;
  uint8_t c2 = scrut0.fst;
  uint64_t input11 = scrut0.snd;
  K___uint8_t_uint64_t uu____296 = Hacl_Bignum_addcarry_u64(c2, input2, (uint64_t)0U);
  K___uint8_t_uint64_t scrut1 = uu____296;
  uint8_t c3 = scrut1.fst;
  uint64_t input21 = scrut1.snd;
  K___uint8_t_uint64_t uu____303 = Hacl_Bignum_addcarry_u64(c3, input3, (uint64_t)0U);
  K___uint8_t_uint64_t scrut2 = uu____303;
  uint64_t input31 = scrut2.snd;
  uint8_t *output0 = output;
  uint8_t *output1 = output + (uint32_t)8U;
  uint8_t *output2 = output + (uint32_t)16U;
  uint8_t *output3 = output + (uint32_t)24U;
  store64_le(output0, input01);
  store64_le(output1, input11);
  store64_le(output2, input21);
  store64_le(output3, input31);
}

static void Hacl_EC_Format_scalar_of_point(uint8_t *scalar, uint64_t *point)
{
  uint64_t *x = point;
  uint64_t *z = point + (uint32_t)5U;
  uint64_t buf[10U] = { 0U };
  uint64_t *zmone = buf;
  uint64_t *sc = buf + (uint32_t)5U;
  Hacl_Bignum_Crecip_crecip(zmone, z);
  Hacl_Bignum_Fmul_fmul(sc, x, zmone);
  Hacl_EC_Format_fcontract(scalar, sc);
}

void Hacl_EC_crypto_scalarmult(uint8_t *mypublic, uint8_t *secret, uint8_t *basepoint)
{
  uint64_t buf0[10U] = { 0U };
  uint64_t *x0 = buf0;
  uint64_t *z = buf0 + (uint32_t)5U;
  Hacl_EC_Format_fexpand(x0, basepoint);
  z[0U] = (uint64_t)1U;
  uint64_t *q = buf0;
  uint8_t e[32U] = { 0U };
  memcpy(e, secret, (uint32_t)32U * sizeof secret[0U]);
  uint8_t e0 = e[0U];
  uint8_t e31 = e[31U];
  uint8_t e01 = e0 & (uint8_t)248U;
  uint8_t e311 = e31 & (uint8_t)127U;
  uint8_t e312 = e311 | (uint8_t)64U;
  e[0U] = e01;
  e[31U] = e312;
  uint8_t *scalar = e;
  uint64_t buf[15U] = { 0U };
  uint64_t *nq = buf;
  uint64_t *x = nq;
  x[0U] = (uint64_t)1U;
  Hacl_EC_Ladder_cmult(nq, scalar, q);
  Hacl_EC_Format_scalar_of_point(mypublic, nq);
}

void Hacl_Curve25519_crypto_scalarmult(uint8_t *mypublic, uint8_t *secret, uint8_t *basepoint)
{
  Hacl_EC_crypto_scalarmult(mypublic, secret, basepoint);
}

