/* This file was auto-generated by KreMLin! */

#include "Hacl_Test_X25519.h"

int32_t main()
{
  uint32_t keysize = (uint32_t)32U;
  uint8_t result[32U] = { 0U };
  uint8_t
  scalar11[32U] =
    {
      (uint8_t)0xa5U, (uint8_t)0x46U, (uint8_t)0xe3U, (uint8_t)0x6bU, (uint8_t)0xf0U, (uint8_t)0x52U,
      (uint8_t)0x7cU, (uint8_t)0x9dU, (uint8_t)0x3bU, (uint8_t)0x16U, (uint8_t)0x15U, (uint8_t)0x4bU,
      (uint8_t)0x82U, (uint8_t)0x46U, (uint8_t)0x5eU, (uint8_t)0xddU, (uint8_t)0x62U, (uint8_t)0x14U,
      (uint8_t)0x4cU, (uint8_t)0x0aU, (uint8_t)0xc1U, (uint8_t)0xfcU, (uint8_t)0x5aU, (uint8_t)0x18U,
      (uint8_t)0x50U, (uint8_t)0x6aU, (uint8_t)0x22U, (uint8_t)0x44U, (uint8_t)0xbaU, (uint8_t)0x44U,
      (uint8_t)0x9aU, (uint8_t)0xc4U
    };
  uint8_t
  scalar21[32U] =
    {
      (uint8_t)0x4bU, (uint8_t)0x66U, (uint8_t)0xe9U, (uint8_t)0xd4U, (uint8_t)0xd1U, (uint8_t)0xb4U,
      (uint8_t)0x67U, (uint8_t)0x3cU, (uint8_t)0x5aU, (uint8_t)0xd2U, (uint8_t)0x26U, (uint8_t)0x91U,
      (uint8_t)0x95U, (uint8_t)0x7dU, (uint8_t)0x6aU, (uint8_t)0xf5U, (uint8_t)0xc1U, (uint8_t)0x1bU,
      (uint8_t)0x64U, (uint8_t)0x21U, (uint8_t)0xe0U, (uint8_t)0xeaU, (uint8_t)0x01U, (uint8_t)0xd4U,
      (uint8_t)0x2cU, (uint8_t)0xa4U, (uint8_t)0x16U, (uint8_t)0x9eU, (uint8_t)0x79U, (uint8_t)0x18U,
      (uint8_t)0xbaU, (uint8_t)0x0dU
    };
  uint8_t
  input11[32U] =
    {
      (uint8_t)0xe6U, (uint8_t)0xdbU, (uint8_t)0x68U, (uint8_t)0x67U, (uint8_t)0x58U, (uint8_t)0x30U,
      (uint8_t)0x30U, (uint8_t)0xdbU, (uint8_t)0x35U, (uint8_t)0x94U, (uint8_t)0xc1U, (uint8_t)0xa4U,
      (uint8_t)0x24U, (uint8_t)0xb1U, (uint8_t)0x5fU, (uint8_t)0x7cU, (uint8_t)0x72U, (uint8_t)0x66U,
      (uint8_t)0x24U, (uint8_t)0xecU, (uint8_t)0x26U, (uint8_t)0xb3U, (uint8_t)0x35U, (uint8_t)0x3bU,
      (uint8_t)0x10U, (uint8_t)0xa9U, (uint8_t)0x03U, (uint8_t)0xa6U, (uint8_t)0xd0U, (uint8_t)0xabU,
      (uint8_t)0x1cU, (uint8_t)0x4cU
    };
  uint8_t
  input21[32U] =
    {
      (uint8_t)0xe5U, (uint8_t)0x21U, (uint8_t)0x0fU, (uint8_t)0x12U, (uint8_t)0x78U, (uint8_t)0x68U,
      (uint8_t)0x11U, (uint8_t)0xd3U, (uint8_t)0xf4U, (uint8_t)0xb7U, (uint8_t)0x95U, (uint8_t)0x9dU,
      (uint8_t)0x05U, (uint8_t)0x38U, (uint8_t)0xaeU, (uint8_t)0x2cU, (uint8_t)0x31U, (uint8_t)0xdbU,
      (uint8_t)0xe7U, (uint8_t)0x10U, (uint8_t)0x6fU, (uint8_t)0xc0U, (uint8_t)0x3cU, (uint8_t)0x3eU,
      (uint8_t)0xfcU, (uint8_t)0x4cU, (uint8_t)0xd5U, (uint8_t)0x49U, (uint8_t)0xc7U, (uint8_t)0x15U,
      (uint8_t)0xa4U, (uint8_t)0x93U
    };
  uint8_t
  expected11[32U] =
    {
      (uint8_t)0xc3U, (uint8_t)0xdaU, (uint8_t)0x55U, (uint8_t)0x37U, (uint8_t)0x9dU, (uint8_t)0xe9U,
      (uint8_t)0xc6U, (uint8_t)0x90U, (uint8_t)0x8eU, (uint8_t)0x94U, (uint8_t)0xeaU, (uint8_t)0x4dU,
      (uint8_t)0xf2U, (uint8_t)0x8dU, (uint8_t)0x08U, (uint8_t)0x4fU, (uint8_t)0x32U, (uint8_t)0xecU,
      (uint8_t)0xcfU, (uint8_t)0x03U, (uint8_t)0x49U, (uint8_t)0x1cU, (uint8_t)0x71U, (uint8_t)0xf7U,
      (uint8_t)0x54U, (uint8_t)0xb4U, (uint8_t)0x07U, (uint8_t)0x55U, (uint8_t)0x77U, (uint8_t)0xa2U,
      (uint8_t)0x85U, (uint8_t)0x52U
    };
  uint8_t
  expected21[32U] =
    {
      (uint8_t)0x95U, (uint8_t)0xcbU, (uint8_t)0xdeU, (uint8_t)0x94U, (uint8_t)0x76U, (uint8_t)0xe8U,
      (uint8_t)0x90U, (uint8_t)0x7dU, (uint8_t)0x7aU, (uint8_t)0xadU, (uint8_t)0xe4U, (uint8_t)0x5cU,
      (uint8_t)0xb4U, (uint8_t)0xb8U, (uint8_t)0x73U, (uint8_t)0xf8U, (uint8_t)0x8bU, (uint8_t)0x59U,
      (uint8_t)0x5aU, (uint8_t)0x68U, (uint8_t)0x79U, (uint8_t)0x9fU, (uint8_t)0xa1U, (uint8_t)0x52U,
      (uint8_t)0xe6U, (uint8_t)0xf8U, (uint8_t)0xf7U, (uint8_t)0x64U, (uint8_t)0x7aU, (uint8_t)0xacU,
      (uint8_t)0x79U, (uint8_t)0x57U
    };
  Hacl_EC_crypto_scalarmult(result, scalar11, input11);
  TestLib_compare_and_print("Curve25519", expected11, result, keysize);
  Hacl_EC_crypto_scalarmult(result, scalar21, input21);
  TestLib_compare_and_print("Curve25519", expected21, result, keysize);
  return exit_success;
}

