/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_Test_X25519_H
#define __Hacl_Test_X25519_H


#include "Hacl_Curve25519.h"
#include "testlib.h"

int32_t main();
#endif
