/* This file was auto-generated by KreMLin! */

#include "Hacl_Curve25519.h"

inline static K___uint8_t_uint64_t
Hacl_Bignum_fmul_by_word(
  uint64_t *tmp,
  uint64_t *input2,
  uint64_t word,
  uint32_t j,
  uint8_t c,
  uint64_t h0,
  uint64_t h1
)
{
  if (j < (uint32_t)4U)
  {
    uint64_t tmpj = tmp[j];
    uint64_t uu____1683 = input2[j];
    uint64_t low = Hacl_Bignum_mulx_u64(word, uu____1683, h1);
    uint8_t c1 = Hacl_Bignum_addcarry_u64(c, low, h0, tmpj);
    tmp[j] = tmpj;
    return Hacl_Bignum_fmul_by_word(tmp, input2, word, j + (uint32_t)1U, c1, h1, h1);
  }
  else
    return ((K___uint8_t_uint64_t){ .fst = c, .snd = h0 });
}

static K___K___uint8_t_uint8_t_uint64_t
Hacl_Bignum_fmul_inner(
  uint64_t *tmp,
  uint64_t word,
  uint64_t *input2,
  uint32_t i,
  uint32_t j,
  uint8_t c,
  uint8_t d,
  uint64_t h0,
  uint64_t h1
)
{
  if (j < (uint32_t)4U)
  {
    uint64_t tmpij = tmp[i + j];
    uint64_t uu____1847 = input2[j];
    uint64_t low = Hacl_Bignum_mulx_u64(word, uu____1847, h1);
    uint8_t c1 = Hacl_Bignum_addcarry_u64(c, low, h0, h0);
    uint8_t d1 = Hacl_Bignum_addcarry_u64(d, tmpij, h0, tmpij);
    tmp[i + j] = tmpij;
    return Hacl_Bignum_fmul_inner(tmp, word, input2, i, j + (uint32_t)1U, c1, d1, h1, h1);
  }
  else
    return ((K___K___uint8_t_uint8_t_uint64_t){ .fst = { .fst = c, .snd = d }, .snd = h0 });
}

inline static void
Hacl_Bignum_fmul_(
  uint64_t *tmp,
  uint64_t *input1,
  uint64_t *input2,
  uint32_t i,
  uint8_t c,
  uint8_t d,
  uint64_t h0,
  uint64_t h1
)
{
  if (i < (uint32_t)4U)
  {
    uint64_t tmpi = tmp[i];
    uint64_t input1i = input1[i];
    uint64_t uu____2037 = input2[0U];
    uint64_t low = Hacl_Bignum_mulx_u64(input1i, uu____2037, h0);
    uint8_t c1 = (uint8_t)0U;
    uint8_t d1 = Hacl_Bignum_addcarry_u64(d, tmpi, low, tmpi);
    tmp[i] = tmpi;
    K___K___uint8_t_uint8_t_uint64_t
    uu____2063 = Hacl_Bignum_fmul_inner(tmp, input1i, input2, i, (uint32_t)1U, c1, d1, h0, h1);
    uint64_t h01 = uu____2063.snd;
    uint8_t d2 = uu____2063.fst.snd;
    uint8_t c2 = uu____2063.fst.fst;
    uint8_t c3 = Hacl_Bignum_addcarry_u64(c2, h01, (uint64_t)0U, h01);
    uint64_t tmpi4 = tmp[i + (uint32_t)4U];
    uint8_t d3 = Hacl_Bignum_addcarry_u64(d2, h01, (uint64_t)0U, tmpi4);
    tmp[i + (uint32_t)4U] = tmpi4;
    Hacl_Bignum_fmul_(tmp, input1, input2, i + (uint32_t)1U, c3, d3, h01, h1);
  }
}

inline static void Hacl_Bignum_fmul(uint64_t *output, uint64_t *input1, uint64_t *input2)
{
  uint64_t tmp[8U] = { 0U };
  uint64_t h0 = (uint64_t)0U;
  uint64_t h1 = (uint64_t)0U;
  uint64_t uu____2314 = input1[0U];
  uint64_t uu____2335 = input2[0U];
  uint64_t uu____2313 = Hacl_Bignum_mulx_u64(uu____2314, uu____2335, h0);
  tmp[0U] = uu____2313;
  uint8_t c = (uint8_t)0U;
  uint8_t d = (uint8_t)0U;
  uint64_t uu____2365 = input1[0U];
  K___uint8_t_uint64_t
  uu____2360 = Hacl_Bignum_fmul_by_word(tmp, input2, uu____2365, (uint32_t)1U, c, h0, h1);
  K___uint8_t_uint64_t scrut = uu____2360;
  uint8_t c1 = scrut.fst;
  uint64_t h01 = scrut.snd;
  uint64_t tmp4 = tmp[4U];
  uint8_t c2 = Hacl_Bignum_addcarry_u64(c1, h01, (uint64_t)0U, tmp4);
  tmp[4U] = tmp4;
  Hacl_Bignum_fmul_(tmp, input1, input2, (uint32_t)1U, c2, d, h01, h1);
  uint64_t tmp0 = tmp[0U];
  uint64_t tmp1 = tmp[1U];
  uint64_t tmp2 = tmp[2U];
  uint64_t tmp3 = tmp[3U];
  uint64_t tmp41 = tmp[4U];
  uint64_t tmp5 = tmp[5U];
  uint64_t tmp6 = tmp[6U];
  uint64_t tmp7 = tmp[7U];
  uint8_t c3 = (uint8_t)0U;
  uint8_t d1 = (uint8_t)0U;
  uint64_t low = Hacl_Bignum_mulx_u64(tmp41, (uint64_t)38U, h01);
  uint8_t c4 = Hacl_Bignum_addcarry_u64(c3, tmp0, low, tmp0);
  uint64_t low1 = Hacl_Bignum_mulx_u64(tmp5, (uint64_t)38U, h1);
  uint8_t c5 = Hacl_Bignum_addcarry_u64(c4, tmp1, low1, tmp1);
  uint8_t d2 = Hacl_Bignum_addcarry_u64(d1, tmp1, h01, tmp1);
  uint64_t h02 = h1;
  uint64_t low2 = Hacl_Bignum_mulx_u64(tmp6, (uint64_t)38U, h1);
  uint8_t c6 = Hacl_Bignum_addcarry_u64(c5, tmp2, low2, tmp2);
  uint8_t d3 = Hacl_Bignum_addcarry_u64(d2, tmp2, h02, tmp2);
  uint64_t h03 = h1;
  uint64_t low3 = Hacl_Bignum_mulx_u64(tmp7, (uint64_t)38U, h1);
  uint8_t c7 = Hacl_Bignum_addcarry_u64(c6, tmp3, low3, tmp3);
  uint8_t d4 = Hacl_Bignum_addcarry_u64(d3, tmp3, h03, tmp3);
  (void)Hacl_Bignum_addcarry_u64(c7, h1, (uint64_t)0U, h1);
  (void)Hacl_Bignum_addcarry_u64(d4, h1, (uint64_t)0U, h1);
  uint64_t h11 = (uint64_t)38U * h1;
  uint8_t c9 = (uint8_t)0U;
  uint8_t c10 = Hacl_Bignum_addcarry_u64(c9, tmp0, h11, tmp0);
  uint8_t c11 = Hacl_Bignum_addcarry_u64(c10, tmp1, (uint64_t)0U, tmp1);
  uint8_t c12 = Hacl_Bignum_addcarry_u64(c11, tmp2, (uint64_t)0U, tmp2);
  uint8_t c13 = Hacl_Bignum_addcarry_u64(c12, tmp3, (uint64_t)0U, tmp3);
  uint64_t h12 = (uint64_t)38U * (uint64_t)c13;
  uint8_t c14 = (uint8_t)0U;
  uint8_t c15 = Hacl_Bignum_addcarry_u64(c14, tmp0, h12, tmp0);
  uint8_t c16 = Hacl_Bignum_addcarry_u64(c15, tmp1, (uint64_t)0U, tmp1);
  uint8_t c17 = Hacl_Bignum_addcarry_u64(c16, tmp2, (uint64_t)0U, tmp2);
  (void)Hacl_Bignum_addcarry_u64(c17, tmp3, (uint64_t)0U, tmp3);
  output[0U] = tmp0;
  output[1U] = tmp1;
  output[2U] = tmp2;
  output[3U] = tmp3;
}

inline static void Hacl_Bignum_fsquare(uint64_t *input)
{
  Hacl_Bignum_fmul(input, input, input);
}

inline static void Hacl_Bignum_Fmul_fmul(uint64_t *output, uint64_t *input, uint64_t *input21)
{
  Hacl_Bignum_fmul(output, input, input21);
}

inline static void
Hacl_Bignum_Fsquare_fsquare_times(uint64_t *output, uint64_t *input, uint32_t count1)
{
  memcpy(output, input, (uint32_t)5U * sizeof input[0U]);
  Hacl_Bignum_fsquare(output);
  for (uint32_t i = (uint32_t)1U; i < count1; i = i + (uint32_t)1U)
    Hacl_Bignum_fsquare(output);
}

inline static void Hacl_Bignum_Fsquare_fsquare_times_inplace(uint64_t *output, uint32_t count1)
{
  Hacl_Bignum_fsquare(output);
  for (uint32_t i = (uint32_t)1U; i < count1; i = i + (uint32_t)1U)
    Hacl_Bignum_fsquare(output);
}

inline static void Hacl_Bignum_Crecip_crecip(uint64_t *out, uint64_t *z)
{
  uint64_t buf[20U] = { 0U };
  uint64_t *a = buf;
  uint64_t *t00 = buf + (uint32_t)5U;
  uint64_t *b0 = buf + (uint32_t)10U;
  Hacl_Bignum_Fsquare_fsquare_times(a, z, (uint32_t)1U);
  Hacl_Bignum_Fsquare_fsquare_times(t00, a, (uint32_t)2U);
  Hacl_Bignum_Fmul_fmul(b0, t00, z);
  Hacl_Bignum_Fmul_fmul(a, b0, a);
  Hacl_Bignum_Fsquare_fsquare_times(t00, a, (uint32_t)1U);
  Hacl_Bignum_Fmul_fmul(b0, t00, b0);
  Hacl_Bignum_Fsquare_fsquare_times(t00, b0, (uint32_t)5U);
  uint64_t *t01 = buf + (uint32_t)5U;
  uint64_t *b1 = buf + (uint32_t)10U;
  uint64_t *c0 = buf + (uint32_t)15U;
  Hacl_Bignum_Fmul_fmul(b1, t01, b1);
  Hacl_Bignum_Fsquare_fsquare_times(t01, b1, (uint32_t)10U);
  Hacl_Bignum_Fmul_fmul(c0, t01, b1);
  Hacl_Bignum_Fsquare_fsquare_times(t01, c0, (uint32_t)20U);
  Hacl_Bignum_Fmul_fmul(t01, t01, c0);
  Hacl_Bignum_Fsquare_fsquare_times_inplace(t01, (uint32_t)10U);
  Hacl_Bignum_Fmul_fmul(b1, t01, b1);
  Hacl_Bignum_Fsquare_fsquare_times(t01, b1, (uint32_t)50U);
  uint64_t *a0 = buf;
  uint64_t *t0 = buf + (uint32_t)5U;
  uint64_t *b = buf + (uint32_t)10U;
  uint64_t *c = buf + (uint32_t)15U;
  Hacl_Bignum_Fmul_fmul(c, t0, b);
  Hacl_Bignum_Fsquare_fsquare_times(t0, c, (uint32_t)100U);
  Hacl_Bignum_Fmul_fmul(t0, t0, c);
  Hacl_Bignum_Fsquare_fsquare_times_inplace(t0, (uint32_t)50U);
  Hacl_Bignum_Fmul_fmul(t0, t0, b);
  Hacl_Bignum_Fsquare_fsquare_times_inplace(t0, (uint32_t)5U);
  Hacl_Bignum_Fmul_fmul(out, t0, a0);
}

inline static void Hacl_Bignum_Fdifference_fdifference(uint64_t *a, uint64_t *b)
{
  uint64_t a0 = a[0U];
  uint64_t a1 = a[1U];
  uint64_t a2 = a[2U];
  uint64_t a3 = a[3U];
  uint64_t b0 = b[0U];
  uint64_t b1 = b[1U];
  uint64_t b2 = b[2U];
  uint64_t b3 = b[3U];
  uint64_t tmp[5U] = { 0U };
  uint64_t tmp0 = tmp[0U];
  uint64_t tmp1 = tmp[1U];
  uint64_t tmp2 = tmp[2U];
  uint64_t tmp3 = tmp[3U];
  uint64_t tmp4 = tmp[4U];
  uint8_t c = (uint8_t)0U;
  uint8_t c1 = Hacl_Bignum_addcarry_u64(c, b0, (uint64_t)0xffffffffffffffdaU, tmp0);
  uint8_t c2 = Hacl_Bignum_addcarry_u64(c1, b1, (uint64_t)0xffffffffffffffffU, tmp1);
  uint8_t c3 = Hacl_Bignum_addcarry_u64(c2, b2, (uint64_t)0xffffffffffffffffU, tmp2);
  uint8_t c4 = Hacl_Bignum_addcarry_u64(c3, b3, (uint64_t)0xffffffffffffffffU, tmp3);
  (void)Hacl_Bignum_addcarry_u64(c4, (uint64_t)0U, (uint64_t)0U, tmp4);
  uint8_t c6 = (uint8_t)0U;
  uint8_t c7 = Hacl_Bignum_subborrow_u64(c6, tmp0, a0, tmp0);
  uint8_t c8 = Hacl_Bignum_subborrow_u64(c7, tmp1, a1, tmp1);
  uint8_t c9 = Hacl_Bignum_subborrow_u64(c8, tmp2, a2, tmp2);
  uint8_t c10 = Hacl_Bignum_subborrow_u64(c9, tmp3, a3, tmp3);
  (void)Hacl_Bignum_subborrow_u64(c10, tmp4, (uint64_t)0U, tmp4);
  uint64_t top = (uint64_t)38U * tmp4;
  uint8_t c12 = (uint8_t)0U;
  uint8_t c13 = Hacl_Bignum_addcarry_u64(c12, tmp0, top, tmp0);
  uint8_t c14 = Hacl_Bignum_addcarry_u64(c13, tmp1, (uint64_t)0U, tmp1);
  uint8_t c15 = Hacl_Bignum_addcarry_u64(c14, tmp2, (uint64_t)0U, tmp2);
  uint8_t c16 = Hacl_Bignum_addcarry_u64(c15, tmp3, (uint64_t)0U, tmp3);
  uint64_t top1 = (uint64_t)38U * (uint64_t)c16;
  uint8_t c17 = (uint8_t)0U;
  uint8_t c18 = Hacl_Bignum_addcarry_u64(c17, tmp0, top1, tmp0);
  uint8_t c19 = Hacl_Bignum_addcarry_u64(c18, tmp1, (uint64_t)0U, tmp1);
  uint8_t c20 = Hacl_Bignum_addcarry_u64(c19, tmp2, (uint64_t)0U, tmp2);
  (void)Hacl_Bignum_addcarry_u64(c20, tmp3, (uint64_t)0U, tmp3);
  a[0U] = tmp0;
  a[1U] = tmp1;
  a[2U] = tmp2;
  a[3U] = tmp3;
}

inline static void Hacl_Bignum_Fscalar_fscalar(uint64_t *output, uint64_t *b, uint64_t s)
{
  uint64_t b0 = b[0U];
  uint64_t b1 = b[1U];
  uint64_t b2 = b[2U];
  uint64_t b3 = b[3U];
  uint64_t h0 = (uint64_t)0U;
  uint64_t h1 = (uint64_t)0U;
  uint64_t h2 = (uint64_t)0U;
  uint64_t h3 = (uint64_t)0U;
  uint64_t h4 = (uint64_t)0U;
  uint64_t l4 = (uint64_t)0U;
  uint64_t l0 = Hacl_Bignum_mulx_u64(b0, s, h0);
  uint64_t l1 = Hacl_Bignum_mulx_u64(b1, s, h1);
  uint64_t l2 = Hacl_Bignum_mulx_u64(b2, s, h2);
  uint64_t l3 = Hacl_Bignum_mulx_u64(b3, s, h3);
  uint8_t c = (uint8_t)0U;
  uint8_t c1 = Hacl_Bignum_addcarry_u64(c, l1, h0, l1);
  uint8_t c2 = Hacl_Bignum_addcarry_u64(c1, l2, h1, l2);
  uint8_t c3 = Hacl_Bignum_addcarry_u64(c2, l3, h2, l3);
  (void)Hacl_Bignum_addcarry_u64(c3, (uint64_t)0U, h3, l4);
  uint64_t l41 = Hacl_Bignum_mulx_u64(l4, (uint64_t)38U, h4);
  uint8_t c5 = (uint8_t)0U;
  uint8_t c6 = Hacl_Bignum_addcarry_u64(c5, l0, l41, l0);
  uint8_t c7 = Hacl_Bignum_addcarry_u64(c6, l1, h4, l1);
  uint8_t c8 = Hacl_Bignum_addcarry_u64(c7, l2, (uint64_t)0U, l2);
  uint8_t c9 = Hacl_Bignum_addcarry_u64(c8, l3, (uint64_t)0U, l3);
  uint64_t l42 = (uint64_t)38U * (uint64_t)c9;
  uint8_t c10 = (uint8_t)0U;
  uint8_t c11 = Hacl_Bignum_addcarry_u64(c10, l0, l42, l0);
  uint8_t c12 = Hacl_Bignum_addcarry_u64(c11, l1, (uint64_t)0U, l1);
  uint8_t c13 = Hacl_Bignum_addcarry_u64(c12, l2, (uint64_t)0U, l2);
  (void)Hacl_Bignum_addcarry_u64(c13, l3, (uint64_t)0U, l3);
  output[0U] = l0;
  output[1U] = l1;
  output[2U] = l2;
  output[3U] = l3;
}

inline static void Hacl_Bignum_Fsum_fsum(uint64_t *a, uint64_t *b)
{
  uint64_t a0 = a[0U];
  uint64_t a1 = a[1U];
  uint64_t a2 = a[2U];
  uint64_t a3 = a[3U];
  uint64_t b0 = b[0U];
  uint64_t b1 = b[1U];
  uint64_t b2 = b[2U];
  uint64_t b3 = b[3U];
  uint8_t c = (uint8_t)0U;
  uint8_t c1 = Hacl_Bignum_addcarry_u64(c, a0, b0, a0);
  uint8_t c2 = Hacl_Bignum_addcarry_u64(c1, a1, b1, a1);
  uint8_t c3 = Hacl_Bignum_addcarry_u64(c2, a2, b2, a2);
  uint8_t c4 = Hacl_Bignum_addcarry_u64(c3, a3, b3, a3);
  uint64_t top = (uint64_t)38U * (uint64_t)c4;
  uint8_t c5 = (uint8_t)0U;
  uint8_t c6 = Hacl_Bignum_addcarry_u64(c5, a0, top, a0);
  uint8_t c7 = Hacl_Bignum_addcarry_u64(c6, a1, (uint64_t)0U, a1);
  uint8_t c8 = Hacl_Bignum_addcarry_u64(c7, a2, (uint64_t)0U, a2);
  (void)Hacl_Bignum_addcarry_u64(c8, a3, (uint64_t)0U, a3);
  a[0U] = a0;
  a[1U] = a1;
  a[2U] = a2;
  a[3U] = a3;
}

static void
Hacl_EC_Point_swap_conditional_step(uint64_t *a, uint64_t *b, uint64_t swap1, uint32_t ctr)
{
  uint32_t i = ctr - (uint32_t)1U;
  uint64_t ai = a[i];
  uint64_t bi = b[i];
  uint64_t x = swap1 & (ai ^ bi);
  uint64_t ai1 = ai ^ x;
  uint64_t bi1 = bi ^ x;
  a[i] = ai1;
  b[i] = bi1;
}

static void
Hacl_EC_Point_swap_conditional_(uint64_t *a, uint64_t *b, uint64_t swap1, uint32_t ctr)
{
  if (!(ctr == (uint32_t)0U))
  {
    Hacl_EC_Point_swap_conditional_step(a, b, swap1, ctr);
    uint32_t i = ctr - (uint32_t)1U;
    Hacl_EC_Point_swap_conditional_(a, b, swap1, i);
  }
}

static void Hacl_EC_Point_swap_conditional(uint64_t *a, uint64_t *b, uint64_t iswap)
{
  uint64_t swap1 = (uint64_t)0U - iswap;
  Hacl_EC_Point_swap_conditional_(a, b, swap1, (uint32_t)5U);
  Hacl_EC_Point_swap_conditional_(a + (uint32_t)5U, b + (uint32_t)5U, swap1, (uint32_t)5U);
}

static void Hacl_EC_Point_copy(uint64_t *output, uint64_t *input)
{
  memcpy(output, input, (uint32_t)5U * sizeof input[0U]);
  memcpy(output + (uint32_t)5U,
    input + (uint32_t)5U,
    (uint32_t)5U * sizeof (input + (uint32_t)5U)[0U]);
}

static void
Hacl_EC_AddAndDouble_fmonty(
  uint64_t *pp,
  uint64_t *ppq,
  uint64_t *p,
  uint64_t *pq,
  uint64_t *qmqp
)
{
  uint64_t *qx = qmqp;
  uint64_t *x2 = pp;
  uint64_t *z2 = pp + (uint32_t)5U;
  uint64_t *x3 = ppq;
  uint64_t *z3 = ppq + (uint32_t)5U;
  uint64_t *x = p;
  uint64_t *z = p + (uint32_t)5U;
  uint64_t *xprime = pq;
  uint64_t *zprime = pq + (uint32_t)5U;
  uint64_t buf[40U] = { 0U };
  uint64_t *origx = buf;
  uint64_t *origxprime = buf + (uint32_t)5U;
  uint64_t *xxprime0 = buf + (uint32_t)25U;
  uint64_t *zzprime0 = buf + (uint32_t)30U;
  memcpy(origx, x, (uint32_t)5U * sizeof x[0U]);
  Hacl_Bignum_Fsum_fsum(x, z);
  Hacl_Bignum_Fdifference_fdifference(z, origx);
  memcpy(origxprime, xprime, (uint32_t)5U * sizeof xprime[0U]);
  Hacl_Bignum_Fsum_fsum(xprime, zprime);
  Hacl_Bignum_Fdifference_fdifference(zprime, origxprime);
  Hacl_Bignum_Fmul_fmul(xxprime0, xprime, z);
  Hacl_Bignum_Fmul_fmul(zzprime0, x, zprime);
  uint64_t *origxprime0 = buf + (uint32_t)5U;
  uint64_t *xx0 = buf + (uint32_t)15U;
  uint64_t *zz0 = buf + (uint32_t)20U;
  uint64_t *xxprime = buf + (uint32_t)25U;
  uint64_t *zzprime = buf + (uint32_t)30U;
  uint64_t *zzzprime = buf + (uint32_t)35U;
  memcpy(origxprime0, xxprime, (uint32_t)5U * sizeof xxprime[0U]);
  Hacl_Bignum_Fsum_fsum(xxprime, zzprime);
  Hacl_Bignum_Fdifference_fdifference(zzprime, origxprime0);
  Hacl_Bignum_Fsquare_fsquare_times(x3, xxprime, (uint32_t)1U);
  Hacl_Bignum_Fsquare_fsquare_times(zzzprime, zzprime, (uint32_t)1U);
  Hacl_Bignum_Fmul_fmul(z3, zzzprime, qx);
  Hacl_Bignum_Fsquare_fsquare_times(xx0, x, (uint32_t)1U);
  Hacl_Bignum_Fsquare_fsquare_times(zz0, z, (uint32_t)1U);
  uint64_t *zzz = buf + (uint32_t)10U;
  uint64_t *xx = buf + (uint32_t)15U;
  uint64_t *zz = buf + (uint32_t)20U;
  Hacl_Bignum_Fmul_fmul(x2, xx, zz);
  Hacl_Bignum_Fdifference_fdifference(zz, xx);
  uint64_t scalar = (uint64_t)121665U;
  Hacl_Bignum_Fscalar_fscalar(zzz, zz, scalar);
  Hacl_Bignum_Fsum_fsum(zzz, xx);
  Hacl_Bignum_Fmul_fmul(z2, zzz, zz);
}

static void
Hacl_EC_Ladder_SmallLoop_cmult_small_loop_step(
  uint64_t *nq,
  uint64_t *nqpq,
  uint64_t *nq2,
  uint64_t *nqpq2,
  uint64_t *q,
  uint8_t byt
)
{
  uint64_t bit = (uint64_t)(byt >> (uint32_t)7U);
  Hacl_EC_Point_swap_conditional(nq, nqpq, bit);
  Hacl_EC_AddAndDouble_fmonty(nq2, nqpq2, nq, nqpq, q);
  uint64_t bit0 = (uint64_t)(byt >> (uint32_t)7U);
  Hacl_EC_Point_swap_conditional(nq2, nqpq2, bit0);
}

static void
Hacl_EC_Ladder_SmallLoop_cmult_small_loop_double_step(
  uint64_t *nq,
  uint64_t *nqpq,
  uint64_t *nq2,
  uint64_t *nqpq2,
  uint64_t *q,
  uint8_t byt
)
{
  Hacl_EC_Ladder_SmallLoop_cmult_small_loop_step(nq, nqpq, nq2, nqpq2, q, byt);
  uint8_t byt1 = byt << (uint32_t)1U;
  Hacl_EC_Ladder_SmallLoop_cmult_small_loop_step(nq2, nqpq2, nq, nqpq, q, byt1);
}

static void
Hacl_EC_Ladder_SmallLoop_cmult_small_loop(
  uint64_t *nq,
  uint64_t *nqpq,
  uint64_t *nq2,
  uint64_t *nqpq2,
  uint64_t *q,
  uint8_t byt,
  uint32_t i
)
{
  if (!(i == (uint32_t)0U))
  {
    uint32_t i_ = i - (uint32_t)1U;
    Hacl_EC_Ladder_SmallLoop_cmult_small_loop_double_step(nq, nqpq, nq2, nqpq2, q, byt);
    uint8_t byt_ = byt << (uint32_t)2U;
    Hacl_EC_Ladder_SmallLoop_cmult_small_loop(nq, nqpq, nq2, nqpq2, q, byt_, i_);
  }
}

static void
Hacl_EC_Ladder_BigLoop_cmult_big_loop(
  uint8_t *n1,
  uint64_t *nq,
  uint64_t *nqpq,
  uint64_t *nq2,
  uint64_t *nqpq2,
  uint64_t *q,
  uint32_t i
)
{
  if (!(i == (uint32_t)0U))
  {
    uint32_t i1 = i - (uint32_t)1U;
    uint8_t byte = n1[i1];
    Hacl_EC_Ladder_SmallLoop_cmult_small_loop(nq, nqpq, nq2, nqpq2, q, byte, (uint32_t)4U);
    Hacl_EC_Ladder_BigLoop_cmult_big_loop(n1, nq, nqpq, nq2, nqpq2, q, i1);
  }
}

static void Hacl_EC_Ladder_cmult(uint64_t *result, uint8_t *n1, uint64_t *q)
{
  uint64_t point_buf[40U] = { 0U };
  uint64_t *nq = point_buf;
  uint64_t *nqpq = point_buf + (uint32_t)10U;
  uint64_t *nq2 = point_buf + (uint32_t)20U;
  uint64_t *nqpq2 = point_buf + (uint32_t)30U;
  Hacl_EC_Point_copy(nqpq, q);
  nq[0U] = (uint64_t)1U;
  Hacl_EC_Ladder_BigLoop_cmult_big_loop(n1, nq, nqpq, nq2, nqpq2, q, (uint32_t)32U);
  Hacl_EC_Point_copy(result, nq);
}

static void Hacl_EC_Format_fexpand(uint64_t *output, uint8_t *input)
{
  uint8_t *input0 = input;
  uint8_t *input1 = input + (uint32_t)8U;
  uint8_t *input2 = input + (uint32_t)16U;
  uint8_t *input3 = input + (uint32_t)24U;
  uint64_t uu____425 = load64_le(input0);
  output[0U] = uu____425;
  uint64_t uu____450 = load64_le(input1);
  output[1U] = uu____450;
  uint64_t uu____475 = load64_le(input2);
  output[2U] = uu____475;
  uint64_t uu____500 = load64_le(input3);
  uint64_t uu____499 = uu____500 & (uint64_t)0x7fffffffffffffffU;
  output[3U] = uu____499;
}

static void Hacl_EC_Format_fcontract(uint8_t *output, uint64_t *input)
{
  uint64_t top = input[3U];
  input[3U] = top & (uint64_t)0x7fffffffffffffffU;
  uint64_t input0 = input[0U];
  uint64_t input1 = input[1U];
  uint64_t input2 = input[2U];
  uint64_t input3 = input[3U];
  uint64_t top1 = (uint64_t)19U * (top >> (uint32_t)63U);
  uint8_t c = (uint8_t)0U;
  uint8_t c1 = Hacl_Bignum_addcarry_u64(c, input0, top1, input0);
  uint8_t c2 = Hacl_Bignum_addcarry_u64(c1, input1, (uint64_t)0U, input1);
  uint8_t c3 = Hacl_Bignum_addcarry_u64(c2, input2, (uint64_t)0U, input2);
  (void)Hacl_Bignum_addcarry_u64(c3, input3, (uint64_t)0U, input3);
  uint8_t *output0 = output;
  uint8_t *output1 = output + (uint32_t)8U;
  uint8_t *output2 = output + (uint32_t)16U;
  uint8_t *output3 = output + (uint32_t)24U;
  store64_le(output0, input0);
  store64_le(output1, input1);
  store64_le(output2, input2);
  store64_le(output3, input3);
}

static void Hacl_EC_Format_scalar_of_point(uint8_t *scalar, uint64_t *point)
{
  uint64_t *x = point;
  uint64_t *z = point + (uint32_t)5U;
  uint64_t buf[10U] = { 0U };
  uint64_t *zmone = buf;
  uint64_t *sc = buf + (uint32_t)5U;
  Hacl_Bignum_Crecip_crecip(zmone, z);
  Hacl_Bignum_Fmul_fmul(sc, x, zmone);
  Hacl_EC_Format_fcontract(scalar, sc);
}

void Hacl_EC_crypto_scalarmult(uint8_t *mypublic, uint8_t *secret, uint8_t *basepoint)
{
  uint64_t buf0[10U] = { 0U };
  uint64_t *x0 = buf0;
  uint64_t *z = buf0 + (uint32_t)5U;
  Hacl_EC_Format_fexpand(x0, basepoint);
  z[0U] = (uint64_t)1U;
  uint64_t *q = buf0;
  uint8_t e[32U] = { 0U };
  memcpy(e, secret, (uint32_t)32U * sizeof secret[0U]);
  uint8_t e0 = e[0U];
  uint8_t e31 = e[31U];
  uint8_t e01 = e0 & (uint8_t)248U;
  uint8_t e311 = e31 & (uint8_t)127U;
  uint8_t e312 = e311 | (uint8_t)64U;
  e[0U] = e01;
  e[31U] = e312;
  uint8_t *scalar = e;
  uint64_t buf[15U] = { 0U };
  uint64_t *nq = buf;
  uint64_t *x = nq;
  x[0U] = (uint64_t)1U;
  Hacl_EC_Ladder_cmult(nq, scalar, q);
  Hacl_EC_Format_scalar_of_point(mypublic, nq);
}

void Hacl_Curve25519_crypto_scalarmult(uint8_t *mypublic, uint8_t *secret, uint8_t *basepoint)
{
  Hacl_EC_crypto_scalarmult(mypublic, secret, basepoint);
}

